# Generated by Django 5.0.6 on 2024-07-04 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id_num', models.IntegerField(primary_key=True, serialize=False)),
                ('img_url', models.URLField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('specification', models.CharField(max_length=500, null=True)),
                ('price', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='base',
        ),
        migrations.DeleteModel(
            name='FurnitureProducts',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='products',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom_app.category'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom_app.category'),
        ),
        migrations.DeleteModel(
            name='Base',
        ),
    ]
