# Generated by Django 5.0.6 on 2024-07-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0002_products_subcategory_remove_category_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='specification',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
