# Generated by Django 5.0.6 on 2024-07-09 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0006_products_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='base',
        ),
    ]
