# Generated by Django 5.0.6 on 2024-07-09 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0007_remove_products_base'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='category',
            new_name='sub_category',
        ),
    ]
