# Generated by Django 5.0.6 on 2024-07-09 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0008_rename_category_products_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='base',
            new_name='category',
        ),
    ]
