# Generated by Django 5.0.6 on 2024-07-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0009_rename_base_subcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
