# Generated by Django 5.0.6 on 2024-07-09 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0010_alter_products_img_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='img_url',
            new_name='image',
        ),
    ]
