# Generated by Django 5.0.6 on 2024-07-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0011_rename_img_url_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='changefreq',
            field=models.CharField(choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], default='weekly', max_length=10),
        ),
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='products',
            name='changefreq',
            field=models.CharField(choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], default='daily', max_length=10),
        ),
        migrations.AddField(
            model_name='products',
            name='priority',
            field=models.FloatField(default=0.9),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='changefreq',
            field=models.CharField(choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], default='daily', max_length=10),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='priority',
            field=models.FloatField(default=0.7),
        ),
    ]
